CREATE TABLE IF NOT EXISTS Movie (
    id SERIAL PRIMARY KEY,
    movie_name VARCHAR(255),
    imdb_rating FLOAT
);
--created succcessfully


--**************************************************************************************************************************
Insert 200 Movies with predefined movie names and IMDb ratings
INSERT INTO Movie (movie_name, imdb_rating) VALUES
('The Shawshank Redemption', 9.3),
('Inception', 8.8),
('The Dark Knight', 9.0),
('Forrest Gump', 8.8),
('The Godfather', 9.2),
('Dilwale Dulhania Le Jayenge', 8.2),
('3 Idiots', 8.4),
('Lagaan', 8.1),
('Kabhi Khushi Kabhie Gham', 7.4),
('Zindagi Na Milegi Dobara', 8.1),
('Pulp Fiction', 8.9),
('The Lord of the Rings: The Return of the King', 8.9),
('Sholay', 8.2),
('Mughal-e-Azam', 8.0),
('Dangal', 8.4),
('Jab We Met', 7.9),
('Taare Zameen Par', 8.3),
('The Matrix', 8.7),
('The Lion King', 8.5),
('Kuch Kuch Hota Hai', 7.6),
('Chhichhore', 8.0),
('Fight Club', 8.8),
('A Beautiful Mind', 8.2),
('The Prestige', 8.5),
('The Godfather: Part II', 9.0),
('Pyaasa', 8.2),
('Andhadhun', 8.2),
('Queen', 8.2),
('Kahaani', 8.1),
('Memento', 8.4),
('Schindler’s List', 9.0),
('Aamir', 7.8),
('Gully Boy', 8.0),
('Donnie Darko', 8.1),
('Goodfellas', 8.7),
('Dil Chahta Hai', 8.1),
('Se7en', 8.6),
('V for Vendetta', 8.2),
('Paan Singh Tomar', 8.2),
('Zindagi Na Milegi Dobara', 8.1),
('Kahaani 2: Durga Rani Singh', 6.7),
('The Pursuit of Happyness', 8.0),
('Avengers: Endgame', 8.4),
('The Dark Knight Rises', 8.4),
('Inglourious Basterds', 8.3),
('Kahani', 7.9),
('Bajrangi Bhaijaan', 8.0),
('The Avengers', 8.0),
('Bajirao Mastani', 8.0),
('Black Swan', 8.0),
('The Departed', 8.5),
('The Social Network', 7.7),
('Rehnaa Hai Terre Dil Mein', 7.5),
('Aashiqui 2', 7.3),
('Tanu Weds Manu', 7.1),
('City of God', 8.6),
('Vicky Donor', 7.8),
('A Beautiful Mind', 8.2),
('The Truman Show', 8.1),
('Wag the Dog', 7.6),
('Interstellar', 8.6),
('Joker', 8.5),
('Vikram', 8.4),
('Life of Pi', 8.0),
('My Name Is Khan', 8.0),
('Lage Raho Munna Bhai', 8.0),
('Barfi!', 8.1),
('Taare Zameen Par', 8.3),
('Neerja', 7.7),
('Maidan', 7.9),
('Parasite', 8.6),
('Waqt', 7.6),
('Veer-Zaara', 7.8),
('Mann', 7.5),
('Dil Se', 7.6),
('Kati Patang', 7.2),
('Barfi', 8.1),
('Hera Pheri', 8.2),
('Fukrey', 7.6),
('Goliyon Ki Raasleela Ram-Leela', 7.9),
('Tumhari Sulu', 7.5),
('Gully Boy', 8.0),
('Bhaag Milkha Bhaag', 8.2),
('Rang De Basanti', 8.1),
('Swades', 8.2),
('Chakde! India', 8.0),
('Gully Boy', 8.0),
('Drishyam', 8.2),
('Bajirao Mastani', 8.0),
('Mere Brother Ki Dulhan', 6.8),
('Dhoom 3', 6.2),
('Ek Tha Tiger', 6.9),
('Barfi', 8.1),
('Shakti: The Power', 7.0),
('Raees', 7.8),
('Sultan', 7.8),
('Bajirao Mastani', 8.0),
('Dangal', 8.4),
('Tubelight', 5.5),
('Jab Tak Hai Jaan', 6.7),
('Fifty Shades of Grey', 4.1),
('Titanic', 7.8),
('Mad Max: Fury Road', 8.1),
('Deadpool', 8.0),
('The Revenant', 8.0),
('The Dark Knight', 9.0),
('The Big Short', 7.8),
('The Martian', 8.0),
('Django Unchained', 8.4),
('The Grand Budapest Hotel', 8.1),
('Moonlight', 8.0),
('Whiplash', 8.5),
('Into the Wild', 8.1),
('The Help', 8.1),
('Forrest Gump', 8.8),
('Gladiator', 8.5),
('The Green Mile', 8.6),
('Moulin Rouge!', 7.6),
('12 Angry Men', 9.0),
('The Godfather: Part III', 7.6),
('La La Land', 8.0),
('Your Name', 8.4),
('Catch Me If You Can', 8.1),
('The Pianist', 8.5),
('Schindler’s List', 9.0),
('The Silence of the Lambs', 8.6),
('Goodfellas', 8.7),
('The Great Gatsby', 7.3),
('Pulp Fiction', 8.9),
('Coco', 8.4),
('The Lion King', 8.5),
('Jumanji: Welcome to the Jungle', 6.9),
('The Incredibles', 8.0),
('Indiana Jones and the Last Crusade', 8.2),
('The Lord of the Rings: The Fellowship of the Ring', 8.8),
('Wonder Woman', 7.4),
('Avengers: Infinity War', 8.5),
('Deadpool 2', 7.7),
('Spider-Man: Into the Spider-Verse', 8.4),
('Thor: Ragnarok', 7.9),
('Black Panther', 7.3),
('The Avengers', 8.0),
('Avengers: Age of Ultron', 7.3),
('Shazam!', 7.0),
('Wonder Woman', 7.4),
('The Dark Knight Rises', 8.4),
('Guardians of the Galaxy', 8.0),
('Fantastic Beasts and Where to Find Them', 7.3),
('The Hobbit: An Unexpected Journey', 7.8),
('The Hobbit: The Desolation of Smaug', 7.8),
('The Hobbit: The Battle of the Five Armies', 7.4),
('Star Wars: The Force Awakens', 7.8),
('Star Wars: The Last Jedi', 7.0),
('Star Wars: The Rise of Skywalker', 6.5);

--INSERT successfully executed. 154 rows were affected.


--**************************************************************************************************************************
select * from movie;