CREATE TABLE Theater (
    id SERIAL PRIMARY KEY,
    t_name VARCHAR(250) NOT NULL,
    t_address TEXT NOT NULL,
    city_id INT NOT NULL,
    Hall_count INT NOT NULL,
    CONSTRAINT fk_city FOREIGN KEY (city_id) REFERENCES City (ID)
);
--the theater table is created successufully


--**************************************************************************************************************************
INSERT INTO Theater (t_name, t_address, city_id, Hall_count) VALUES
('PVR Cinemas - Andheri', 'Andheri West, Mumbai', 1, 5),
('INOX Nehru Place', 'Nehru Place, New Delhi', 2, 6),
('Sathyam Cinemas', 'Royapettah, Chennai', 3, 7),
('Cinepolis Kolkata', 'Salt Lake, Kolkata', 4, 4),
('PVR Orion Mall', 'Rajajinagar, Bengaluru', 5, 8),
('Cinemax Ahmedabad', 'Prahlad Nagar, Ahmedabad', 6, 5),
('Wave Cinemas Lucknow', 'Hazratganj, Lucknow', 7, 4),
('Raj Mandir Cinema', 'C-16, Bhagwan Das Rd, Jaipur', 8, 3),
('PVR Hyderabad Central', 'Panjagutta, Hyderabad', 9, 6),
('INOX Trilium Mall', 'Circular Road, Amritsar', 10, 3),
('Carnival Cinemas Bhopal', 'DB Mall, Maharana Pratap Nagar, Bhopal', 11, 4),
('Lulu Mall Cinemas', 'Edapally, Thiruvananthapuram', 12, 5),
('Cinepolis Patna', 'P&M Mall, Patliputra Industrial Area, Patna', 13, 3),
('INOX Bhubaneswar', 'Esplanade One Mall, Rasulgarh, Bhubaneswar', 14, 5),
('Glitz Cinemas Ranchi', 'Nucleus Mall, Circular Road, Ranchi', 15, 4),
('PVR Guwahati', 'City Centre Mall, Guwahati', 16, 6),
('INOX Raipur', 'Magneto The Mall, GE Road, Raipur', 17, 5),
('Carnival Cinemas Chandigarh', 'Elante Mall, Chandigarh', 18, 4),
('PVR Pacific Mall', 'Rajpur Road, Dehradun', 19, 5),
('INOX Goa', 'Caculo Mall, Panaji', 20, 4),
('PVR Oberoi Mall', 'Goregaon East, Mumbai', 1, 6),
('Carnival Cinemas Rohini', 'Sector 10, Rohini, New Delhi', 2, 4),
('Escape Cinemas', 'Express Avenue Mall, Chennai', 3, 7),
('Bioscope Cinemas', 'Axis Mall, Rajarhat, Kolkata', 4, 4),
('Urvashi Cinemas', 'Lalbagh Road, Bengaluru', 5, 8),
('Drive-In Cinema', 'Drive-In Road, Ahmedabad', 6, 5),
('Fun Republic Lucknow', 'Gomti Nagar, Lucknow', 7, 4),
('Ankur Cinema Jaipur', 'MI Road, Jaipur', 8, 3),
('Asian Cinemas Hyderabad', 'Dilsukhnagar, Hyderabad', 9, 6),
('Amritsar Talkies', 'Lawrence Road, Amritsar', 10, 3),
('Platinum Cinemas', 'Habibganj Road, Bhopal', 11, 4),
('Nila Cinemas', 'MG Road, Thiruvananthapuram', 12, 5),
('Vasundhara Cineplex', 'Fraser Road, Patna', 13, 3),
('INOX Janpath', 'Janpath Road, Bhubaneswar', 14, 5),
('Ranchi Cineplex', 'Main Road, Ranchi', 15, 4),
('Central Cinema Hall', 'Paltan Bazar, Guwahati', 16, 6),
('INOX Ambuja City', 'Ambuja Mall, Raipur', 17, 5),
('PVR DT Mall', 'DT Mall, Chandigarh', 18, 4),
('Pacific Cinemas', 'Rajpur Road, Dehradun', 19, 5),
('Cinepolis Goa', 'Mall de Goa, Panaji', 20, 4),
('Phoenix Cinemas - Mumbai', 'Phoenix Mall, Lower Parel, Mumbai', 1, 5),
('PVR Select Citywalk', 'Saket, New Delhi', 2, 6),
('AGS Cinemas', 'Villivakkam, Chennai', 3, 4),
('Navina Cinema', 'Lake Market, Kolkata', 4, 3),
('Forum Mall Cinemas', 'Koramangala, Bengaluru', 5, 8),
('Alpha One Cinemas', 'Vastrapur, Ahmedabad', 6, 5),
('Fun Cinemas Lucknow', 'Riverside Mall, Gomti Nagar, Lucknow', 7, 4),
('Golcha Cinema', 'MI Road, Jaipur', 8, 3),
('Asian GPR Multiplex', 'Kukatpally, Hyderabad', 9, 6),
('City Gold Cinemas', 'Lawrence Road, Amritsar', 10, 3),
('Aura Cinemas', 'Ashoka Garden, Bhopal', 11, 4),
('Cinepolis Lulu Mall', 'Thiruvananthapuram', 12, 5),
('Regent Cinema', 'Fraser Road, Patna', 13, 3),
('Keshari Talkies', 'Janpath Road, Bhubaneswar', 14, 4),
('Capitol Hill Cinema', 'Main Road, Ranchi', 15, 3),
('Gold Cinema', 'Paltan Bazar, Guwahati', 16, 5),
('INOX Magneto Mall', 'GE Road, Raipur', 17, 4),
('Wave Cinemas Chandigarh', 'Industrial Area Phase I, Chandigarh', 18, 5),
('Orient Cinema Hall', 'Clock Tower, Dehradun', 19, 3),
('INOX Mall de Goa', 'NH-17, Porvorim, Goa', 20, 4),
('PVR Mulund', 'R Mall, Mulund West, Mumbai', 1, 6),
('Delite Cinemas', 'Daryaganj, New Delhi', 2, 4),
('Devi Cineplex', 'Anna Salai, Chennai', 3, 5),
('Priya Cinema', 'Deshapriya Park, Kolkata', 4, 4),
('Innovative Multiplex', 'Marathahalli, Bengaluru', 5, 7),
('City Pulse Cinemas', 'Gandhinagar, Ahmedabad', 6, 5),
('Ritz Theater', 'Aminabad, Lucknow', 7, 4),
('Raj Mandir 2', 'C-Scheme, Jaipur', 8, 3),
('Sensation Cinemas', 'Khairatabad, Hyderabad', 9, 6),
('PVR Trillium Mall', 'Circular Road, Amritsar', 10, 3),
('Glitz Cinemas Bhopal', 'New Market, Bhopal', 11, 4),
('Shree Padmanabha Cinema', 'Fort Road, Thiruvananthapuram', 12, 5),
('Vasundhara Vihar', 'Kankarbagh, Patna', 13, 4),
('INOX Bhubaneswar 2', 'Saheed Nagar, Bhubaneswar', 14, 5),
('Ranchi Cineplex 2', 'Circular Road, Ranchi', 15, 4),
('PVR Guwahati 2', 'City Centre Mall, Guwahati', 16, 6),
('Carnival Cinemas Raipur', 'Magneto Mall, Raipur', 17, 4),
('DT Mall Cinemas', 'IT Park, Chandigarh', 18, 4),
('Pacific Hall 2', 'Rajpur Road, Dehradun', 19, 5),
('INOX Goa 2', 'Caculo Mall, Panaji', 20, 4);
--INSERT successfully executed. 80 rows were affected.



--**************************************************************************************************************************
-- Verify the data
select * from Theater;